from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO
from apps.documents.models import Criteria, Evidence, Document
from apps.audit.models import AuditLog


class NAACReportView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, criteria_name):
        try:
            criteria = Criteria.objects.get(name=criteria_name)
        except Criteria.DoesNotExist:
            return Response({'error': 'Criteria not found'}, status=404)

        evidences = Evidence.objects.filter(criteria=criteria)
        documents = Document.objects.filter(evidence__in=evidences, is_approved=True)

        # Generate PDF
        buffer = BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter

        p.drawString(100, height - 100, f"NAAC Report - {criteria.get_name_display()}")
        p.drawString(100, height - 120, f"Generated by: {request.user.username}")

        y = height - 160
        for evidence in evidences:
            p.drawString(100, y, f"Evidence: {evidence.title}")
            y -= 20
            for doc in documents.filter(evidence=evidence):
                p.drawString(120, y, f"- {doc.title} (Approved: {doc.is_approved})")
                y -= 20
                if y < 100:
                    p.showPage()
                    y = height - 100

        p.save()
        buffer.seek(0)

        # Audit log
        AuditLog.objects.create(
            user=request.user,
            action='report_generate',
            resource_type='Report',
            resource_id=0,
            details=f"Generated NAAC report for {criteria_name}"
        )

        response = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="naac_report_{criteria_name}.pdf"'
        return response
